apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sovannlyna-html-v33-certificate
  namespace: sovannlyna-html-v33
spec:
  secretName: sovannlyna-html-v33-secret-tls
  commonName: sovannlyna-html-v33.assessify.org
  dnsNames:
  - sovannlyna-html-v33.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
